### ISSUE TITLE
Add unregister/deregister method to Definition

### ISSUE THREAD

**Issue by assertchris** [krakjoe/componere#1]
❤️

**Comment by krakjoe** [comment]
Since 3227dae1fd7cfd55a6e0f801f1a1b67b757cac69 if you destroy a Definition (or allow it to be destroyed), and that Definition replaced an existing class, the existing class will be restored. If it did not replace an existing class, then you don't really want to destroy it (unstable vm will result).

**Comment by assertchris** [comment]
Good point!
