### ISSUE TITLE
PECL release ?

### ISSUE THREAD

**Issue by remicollet** [krakjoe/componere#2]
Open for discussion

cons:

* more administrative work

pros:

* more visibility (pecl.net still the only site with most used extensions listed)
* DLL automatic build for Windows user

I think is make more sense now that the documentation is on php.net

Of course, if needed, I can take care of the release process ;)

**Comment by krakjoe** [comment]
Sounds good to me, can you take care of creating package on pecl or do I have to do it ?

**Comment by remicollet** [comment]
@krakjoe can you please announce the new extension, on pecl-devel ML, as requested by the new extension process.

Then I can do the remaining stuff

**Comment by krakjoe** [comment]
Done: http://news.php.net/php.pecl.dev/15205

Thanks :)

**Comment by remicollet** [comment]
Great, I think wa have to wait a few days, and I will push last version to pecl.

About the release process, what do you prefer ?

1/ synced release

As we already do for some others ext (apcu, ...)
This means the package.xml need to be in the develop branch, and updated before the tag

2/ async release

You only care of the github release / tag and I will manage the package.xml update + release on pecl
This means the package.xml will only exists in master branch, with the published sources

Second can be simpler for you; but can introduce a small delay, especially when I have some holidays, yes, this may happen ;)

**Comment by krakjoe** [comment]
I like simple, I choose 2 :)

Thanks again :+1: 

I've changed the name of master to release, for clarity.

**Comment by krakjoe** [comment]
It just crossed my mind that I haven't actually checked the build on windows ... 

@weltling could you please run a test build before we do the pecl thing, maybe, if you have a moment ?

**Comment by weltling** [comment]
@krakjoe sure, i'll jump in on this WE to get it done.

Thanks.

**Comment by weltling** [comment]
A quick info - tested with 7.1 through master locally. All tests pass. I'll be working on the AppVeyor support next days.

Thanks.

**Comment by krakjoe** [comment]
Oh nice work on appveyor, I had no idea how to do multi versions like that :)

Looks like we're good to go for pecl then ...

**Comment by weltling** [comment]
Joe, I just saw there are actually no dependencies, so went right ahead, too :) Should be tested faster now with all the versions plus have artifacts. Seems all set for PECL, yeah.

Thanks.

**Comment by krakjoe** [comment]
@weltling just one slight change, we need to run tests with and without opcache enabled ...

**Comment by weltling** [comment]
ACK, i've pushed that part integrating into the same run. Could actually split by the matrix, too. I'll check more a bit later today.

Thanks.

**Comment by krakjoe** [comment]
Cool, with your next change could you add --show-diff so we can see how things have failed please ?

**Comment by weltling** [comment]
Ok, should be all fixed now. I think also, having two test runs within same job should be fine for test time, as otherwise it'll need another build and possibly refetch stuff, etc. Nevertheless, splitting by matrix is doable, for whatever reasons.

Thanks.

**Comment by remicollet** [comment]
@krakjoe I notice some fix in src directory from @weltling for Windows, so can you please tag a new version 2.1.3 to ensure Windows build will be ok on pecl ?

**Comment by remicollet** [comment]
Package registered: https://pecl.php.net/package/componere

**Comment by remicollet** [comment]
v2.1.3 released on PECL
