### ISSUE TITLE
Release v3.1.0

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/componere#22]
- PHP 7.4 support

I think that's all there is to do ... thanks @remicollet :)

**Comment by remicollet** [comment]
@krakjoe I'm a bit busy today with upcoming PHP release (7.1.30, ...) so will probably check this tomorrow

**Comment by krakjoe** [comment]
No problem at all ...

**Comment by remicollet** [comment]
Travis is green
Local QA builds OK

Tagged, released and announced

**Comment by krakjoe** [comment]
Thanks @remicollet
