### ISSUE TITLE
Error: Class 0x01 not found" if Definition( 'MyDerived', 'MyClass' )

### ISSUE THREAD

**Issue by ASchmidt1** [krakjoe/componere#26]
Attached sample worked in previous PHP releases, up to current 7.3. However, it fails with 7.4.2. Therefore, I'm unable to move my project to PHP 7.4.

For an EXISTING class 'MyClass'
```
$myDef = new \Componere\Definition( 'MyDerived', 'MyClass' );
$myDef->addTrait( 'MyTrait' );		--> Error in PHP 7.4.2: Class '' not found
```
where the classname is being reported as 0x01.

Interestingly, for a truly NON-existing class 'NoSuchClass':
```
$myDef = new \Componere\Definition( 'MyDerived', 'NoSuchClass' );
$myDef->addTrait( 'MyTrait' );		
```
neither the constructor NOR the addTrait() will detect the invalid classname!? Of course the resulting  derived class is utterly useless.
[comp74z.txt](https://github.com/krakjoe/componere/files/4168316/comp74z.txt)

**Comment by peter-valkov** [comment]
+1

**Comment by TheCelavi** [comment]
I can confirm this, same issue here.
