### ISSUE TITLE
Release 3.1.2

### ISSUE THREAD

**Issue by remicollet** [krakjoe/componere#34]
Changelog:

* Fix #25 Segfault with OpCache and abstract classes
* Fix #26 Error: Class 0x01 not found" if Definition( 'MyDerived', 'MyClass' ) 
* Fix #29 Protected and Private properties not working as expected
* Fix #30 Can NOT addProperty in extending class
* Compatibility with PHP 8

**Comment by remicollet** [comment]
@krakjoe please review changelog, and I will run the release process
3.1.2 (bugfix) seems ok, not API change

**Comment by krakjoe** [comment]
LGTM, thanks :)

**Comment by remicollet** [comment]
Tagged, released, and announced :)
