### ISSUE TITLE
TypeError when using Componere and Mock objects

### ISSUE THREAD

**Issue by ericnorris** [krakjoe/componere#7]
Hey @krakjoe! Per our discussion in https://github.com/krakjoe/uopz/issues/97, I've taken a look at using `Componere` in place of `uopz`, but have run into a weird issue.

PHP version:
```
-bash-4.2$ php --version
PHP 7.3.2-dev (cli) (built: Dec 22 2018 20:14:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2-dev, Copyright (c) 1999-2018, by Zend Technologies
```

`componere` version:
```
-bash-4.2$ php -r "echo phpversion('componere') . PHP_EOL;"
2.1.4-dev
```

Code:

```php
<?php declare(strict_types=1);

use Componere\Definition;
use Componere\Method;
use Componere\Value;

class A {

    public function foo() : A {
        return $this;
    }
}

class MockA extends A {}

$def      = new Definition(A::class);
$instance = new MockA;

// if you uncomment this, the error goes away
// $instance->foo();

$closure = (new ReflectionClass(MockA::class))
    ->getMethod('foo')
    ->getClosure($instance);

$nested_closure = function(...$args) use ($closure) {
    return $closure(...$args);
};

$def->addMethod('foo', new Method($nested_closure));
$def->register();

// will result in:
// TypeError: Return value of A::foo() must be an instance of A,
// instance of MockA returned
(new A)->foo();
```

Result:
```
-bash-4.2$ php ~/componere_test2.php

Fatal error: Uncaught TypeError: Return value of A::foo() must be an instance of A, instance of MockA returned in /home/enorris/componere_test2.php:10
Stack trace:
#0 /home/enorris/componere_test2.php(27): A->foo()
#1 /home/enorris/componere_test2.php(36): A->foo()
#2 {main}
  thrown in /home/enorris/componere_test2.php on line 10
```

Weirdly enough, if you uncomment the `$instance->foo()` line, there is no error.

**Comment by krakjoe** [comment]
While I can see what this code is trying to do, it's not clear to me why it's trying to do it ...

The problems are clear from the code, I could explain but it would be boring ... in short relinking classes like this is going to cause problems. There's no reasonable way to fix it, however, we can probably code around it if I know what you're trying to do.

I'm going to assume that you're trying to instrument A::foo, you seem to have created MockA so that you can get an instance of a class you're not modifying, so that you can get a closure for the implementation.

```php
<?php declare(strict_types=1);

use Componere\Definition;
use Componere\Method;

class A {

    public function foo() : A {
        return $this;
    }
}

$def = new Definition(A::class);

$prototype = $def->getClosure("foo");

$def->addMethod("foo", new Method(function() use($prototype) {
	echo "instrumented ...\n";
	return $prototype->call($this);
}));
$def->register();

$a = new A();

var_dump($a->foo());
```

Will output

```
instrumented ...
object(A)#3 (0) {
}
```

There are certain rules you must follow when modifying types. I thought a lot about building mocks since we spoke on that bug report and it inspired me to write krakjoe/mimus which you may want to look at ...

Here's some mimus code to do the same thing:

```php
<?php
require "vendor/autoload.php"; // assume class A is autoloaded for brevity ...

use \mimus\Double as double;

$builder = double::class(A::class);
$builder->rule("foo")
	->expects()
	->executes(function(Closure $prototype, ... $args) {
		echo "instrumented ...\n";
		return $prototype(...$args);
	});

$a = new A();
$a->foo();
```

If you're trying to do something I haven't shown, sorry for the misunderstanding, and show me more code :)

**Comment by ericnorris** [comment]
No problem! The code is structured that way because I was trimming down the example from what we ran into at Etsy. In our case, `MockA` is a PHPUnit mock, and moving away from using PHPUnit mocks is not an option for us at this time.

That being said, I have a much smaller example that would break regardless of whether we were using PHPUnit or not:

```php
<?php declare(strict_types=1);

use Componere\Definition;

class A {
    public function foo() : A {
        return $this;
    }
}

class B extends A {}

echo (is_subclass_of(B::class, A::class) ? "true" : "false") . PHP_EOL;

$definition = new Definition(A::class);
$definition->register();

echo (is_subclass_of(B::class, A::class) ? "true" : "false") . PHP_EOL;

(new B)->foo();
```

Output:
```
-bash-4.2$ php componere_test3.php
true
false

Fatal error: Uncaught TypeError: Return value of A::foo() must be an instance of A, instance of B returned in /home/enorris/componere_test3.php:7
Stack trace:
#0 /home/enorris/componere_test3.php(20): A->foo()
#1 {main}
  thrown in /home/enorris/componere_test3.php on line 7
```

After the `Componere\Definition` is registered, B is no longer a subclass of A. Unfortunately this would break a lot of code that relies on using a "fluent" style interface, and potentially cause other issues where the `A` was used as a type but `B` was returned or passed in.

**Comment by ericnorris** [comment]
As a followup, my hunch (although I'm not super familiar with PHP internals) is that:

https://github.com/krakjoe/componere/blob/a8d4e3f7597dc22b50b30ea646932f24d26382a4/src/definition.c#L456

may be the cause as it is not taking the class hierarchy into account, and is replacing the class definition with another. This means that any class that originally extended `A` is not considered a subclass of `A` because `A` in the class table now refers to `o->ce`.

**Comment by krakjoe** [comment]
I've spent a while coming up with something ...

3b06c4f6f7c2dd3792c517751cb154353a991e8c

Allows your original example code to run as you expected ... but I'm not really sure about this, it's been a long day ...

**Comment by krakjoe** [comment]
Well travis liked it but appveyor didn't ... pushed an attempted (blind) fix for that ...

**Comment by ericnorris** [comment]
Thanks for the quick response! We've tested using https://github.com/krakjoe/componere/commit/3b06c4f6f7c2dd3792c517751cb154353a991e8c and it appears to solve the issue we ran into.

I'll leave this issue open so that you can close it when you feel comfortable with the fix. I appreciate you looking into this :)

**Comment by krakjoe** [comment]
LGTM, closing now ... will be in next release ...
