### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/componere#8]
Changelog:

  * Fix #9 crash collecting coverage with phpdbg
  * Fix #10 prototype incorrectly set causing incorrect scope detection
  * Fix #11 Method::setFinal
 *  Fix #12 Method names reflection
 *  Fix #13 Assertion failure in zend_function_dtor
 *  Fix #14 Unexpected trait behaviour
 *  Fix #7 Inheritance tree broken by registering new classes
 *  Fix #15 Classes not being restored on definition destruction
 *  Fix #16 Constant AST not updated
 *  Fix #18 unexpected behaviour when name and parent refer to same class
 *  Definition::setConstant
 *  Drop 7.0 support

**Comment by krakjoe** [comment]
Delay another few days, I'm working on something tricky ...

**Comment by krakjoe** [comment]
Ready when you are @remicollet :)

**Comment by remicollet** [comment]
Tagged, Built, Released and announced

**Comment by remicollet** [comment]
@krakjoe I really like your **Pink Hat** ;)

**Comment by krakjoe** [comment]
Thanks for release, and THANKS for compliment :heart:
